// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    'index',
    {
      type: 'category',
      label: 'OnlySwaps Protocol (v2)',
      link: { type: 'generated-index', slug: '/v2' },
      items: [{ type: 'autogenerated', dirName: 'v2' }],
    },
    {
      type: 'category',
      label: 'Getting Started',
      link: { type: 'generated-index', slug: '/getting-started' },
      items: [{ type: 'autogenerated', dirName: 'getting-started' }],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      link: { type: 'generated-index', slug: '/core-concepts' },
      items: [{ type: 'autogenerated', dirName: 'core-concepts' }],
    },
    {
      type: 'category',
      label: 'Reference',
      link: { type: 'generated-index', slug: '/reference' },
      items: [
        {
          type: 'category',
          label: 'Solidity',
          link: { type: 'generated-index', slug: '/reference/solidity' },
          items: [{ type: 'autogenerated', dirName: 'reference/solidity' }],
        },
        {
          type: 'category',
          label: 'Rust Solver',
          link: { type: 'generated-index', slug: '/reference/rust-solver' },
          items: [{ type: 'autogenerated', dirName: 'reference/rust-solver' }],
        },
        {
          type: 'category',
          label: 'JS SDK',
          link: { type: 'generated-index', slug: '/reference/js' },
          items: [{ type: 'autogenerated', dirName: 'reference/js' }],
        },
      ],
    },
    {
      type: 'category',
      label: 'Operations',
      link: { type: 'generated-index', slug: '/operations' },
      items: [{ type: 'autogenerated', dirName: 'operations' }],
    },
    {
      type: 'category',
      label: 'Recipes',
      link: { type: 'generated-index', slug: '/recipes' },
      items: [{ type: 'autogenerated', dirName: 'recipes' }],
    },
    {
      type: 'category',
      label: 'Contributing',
      link: { type: 'generated-index', slug: '/contributing' },
      items: [{ type: 'autogenerated', dirName: 'contributing' }],
    },
    'changelog',
    'glossary',
  ],
};

export default sidebars;
